"""
Phase 3 - All LLM-Generated Parameters (Combined)
Generated by: claude-sonnet-4-20250514
Timestamp: 2026-04-13 19:09:34 UTC
Mirrors the structure of archetype_params.ARCHETYPE_PARAMS.
"""

GENERATED_PARAMS = {
    "oracle": {
        "preflop": {
            "br": 0.33,
            "vbr": 0.9,
            "cr": 0.33,
            "mbr": 0.45,
            "strong_raise": 0.5,
            "strong_call": 0.4,
            "strong_fold": 0.1,
            "med_raise": 0.15,
            "weak_call": 0.12
        },
        "flop": {
            "br": 0.33,
            "vbr": 0.9,
            "cr": 0.33,
            "mbr": 0.45,
            "strong_raise": 0.5,
            "strong_call": 0.4,
            "strong_fold": 0.1,
            "med_raise": 0.15,
            "weak_call": 0.1
        },
        "turn": {
            "br": 0.3,
            "vbr": 0.85,
            "cr": 0.33,
            "mbr": 0.4,
            "strong_raise": 0.5,
            "strong_call": 0.4,
            "strong_fold": 0.1,
            "med_raise": 0.12,
            "weak_call": 0.08
        },
        "river": {
            "br": 0.28,
            "vbr": 0.8,
            "cr": 0.33,
            "mbr": 0.35,
            "strong_raise": 0.5,
            "strong_call": 0.4,
            "strong_fold": 0.1,
            "med_raise": 0.1,
            "weak_call": 0.06
        }
    },
    "sentinel": {
        "preflop": {
            "br": 0.1,
            "vbr": 0.95,
            "cr": 0.25,
            "mbr": 0.15,
            "strong_raise": 0.65,
            "strong_call": 0.3,
            "strong_fold": 0.05,
            "med_raise": 0.05,
            "weak_call": 0.1
        },
        "flop": {
            "br": 0.08,
            "vbr": 0.9,
            "cr": 0.3,
            "mbr": 0.25,
            "strong_raise": 0.6,
            "strong_call": 0.35,
            "strong_fold": 0.05,
            "med_raise": 0.1,
            "weak_call": 0.08
        },
        "turn": {
            "br": 0.08,
            "vbr": 0.9,
            "cr": 0.32,
            "mbr": 0.2,
            "strong_raise": 0.55,
            "strong_call": 0.4,
            "strong_fold": 0.05,
            "med_raise": 0.08,
            "weak_call": 0.06
        },
        "river": {
            "br": 0.05,
            "vbr": 0.85,
            "cr": 0.35,
            "mbr": 0.15,
            "strong_raise": 0.5,
            "strong_call": 0.4,
            "strong_fold": 0.1,
            "med_raise": 0.05,
            "weak_call": 0.04
        }
    },
    "firestorm": {
        "preflop": {
            "br": 0.7,
            "vbr": 0.98,
            "cr": 0.35,
            "mbr": 0.8,
            "strong_raise": 0.75,
            "strong_call": 0.2,
            "strong_fold": 0.05,
            "med_raise": 0.15,
            "weak_call": 0.4
        },
        "flop": {
            "br": 0.65,
            "vbr": 0.95,
            "cr": 0.3,
            "mbr": 0.75,
            "strong_raise": 0.7,
            "strong_call": 0.25,
            "strong_fold": 0.05,
            "med_raise": 0.2,
            "weak_call": 0.35
        },
        "turn": {
            "br": 0.6,
            "vbr": 0.92,
            "cr": 0.25,
            "mbr": 0.7,
            "strong_raise": 0.65,
            "strong_call": 0.3,
            "strong_fold": 0.05,
            "med_raise": 0.15,
            "weak_call": 0.3
        },
        "river": {
            "br": 0.55,
            "vbr": 0.9,
            "cr": 0.2,
            "mbr": 0.65,
            "strong_raise": 0.6,
            "strong_call": 0.35,
            "strong_fold": 0.05,
            "med_raise": 0.1,
            "weak_call": 0.25
        }
    },
    "wall": {
        "preflop": {
            "br": 0.01,
            "vbr": 0.25,
            "cr": 0.85,
            "mbr": 0.08,
            "strong_raise": 0.02,
            "strong_call": 0.96,
            "strong_fold": 0.02,
            "med_raise": 0.01,
            "weak_call": 0.55
        },
        "flop": {
            "br": 0.05,
            "vbr": 0.5,
            "cr": 0.82,
            "mbr": 0.12,
            "strong_raise": 0.12,
            "strong_call": 0.82,
            "strong_fold": 0.06,
            "med_raise": 0.03,
            "weak_call": 0.5
        },
        "turn": {
            "br": 0.03,
            "vbr": 0.45,
            "cr": 0.82,
            "mbr": 0.1,
            "strong_raise": 0.1,
            "strong_call": 0.82,
            "strong_fold": 0.08,
            "med_raise": 0.02,
            "weak_call": 0.42
        },
        "river": {
            "br": 0.02,
            "vbr": 0.4,
            "cr": 0.82,
            "mbr": 0.08,
            "strong_raise": 0.08,
            "strong_call": 0.82,
            "strong_fold": 0.1,
            "med_raise": 0.01,
            "weak_call": 0.35
        }
    },
    "phantom": {
        "preflop": {
            "br": 0.65,
            "vbr": 0.7,
            "cr": 0.55,
            "mbr": 0.6,
            "strong_raise": 0.45,
            "strong_call": 0.4,
            "strong_fold": 0.15,
            "med_raise": 0.25,
            "weak_call": 0.35
        },
        "flop": {
            "br": 0.55,
            "vbr": 0.6,
            "cr": 0.45,
            "mbr": 0.5,
            "strong_raise": 0.35,
            "strong_call": 0.45,
            "strong_fold": 0.2,
            "med_raise": 0.2,
            "weak_call": 0.3
        },
        "turn": {
            "br": 0.5,
            "vbr": 0.55,
            "cr": 0.4,
            "mbr": 0.45,
            "strong_raise": 0.3,
            "strong_call": 0.45,
            "strong_fold": 0.25,
            "med_raise": 0.15,
            "weak_call": 0.22
        },
        "river": {
            "br": 0.45,
            "vbr": 0.5,
            "cr": 0.35,
            "mbr": 0.4,
            "strong_raise": 0.25,
            "strong_call": 0.45,
            "strong_fold": 0.3,
            "med_raise": 0.1,
            "weak_call": 0.15
        }
    },
    "predator_baseline": {
        "preflop": {
            "br": 0.25,
            "vbr": 0.9,
            "cr": 0.35,
            "mbr": 0.4,
            "strong_raise": 0.6,
            "strong_call": 0.35,
            "strong_fold": 0.05,
            "med_raise": 0.15,
            "weak_call": 0.12
        },
        "flop": {
            "br": 0.25,
            "vbr": 0.85,
            "cr": 0.32,
            "mbr": 0.35,
            "strong_raise": 0.55,
            "strong_call": 0.38,
            "strong_fold": 0.07,
            "med_raise": 0.12,
            "weak_call": 0.1
        },
        "turn": {
            "br": 0.2,
            "vbr": 0.8,
            "cr": 0.3,
            "mbr": 0.3,
            "strong_raise": 0.5,
            "strong_call": 0.42,
            "strong_fold": 0.08,
            "med_raise": 0.1,
            "weak_call": 0.08
        },
        "river": {
            "br": 0.15,
            "vbr": 0.8,
            "cr": 0.28,
            "mbr": 0.25,
            "strong_raise": 0.45,
            "strong_call": 0.45,
            "strong_fold": 0.1,
            "med_raise": 0.08,
            "weak_call": 0.06
        }
    },
    "mirror_default": {
        "preflop": {
            "br": 0.12,
            "vbr": 0.9,
            "cr": 0.33,
            "mbr": 0.3,
            "strong_raise": 0.62,
            "strong_call": 0.33,
            "strong_fold": 0.05,
            "med_raise": 0.15,
            "weak_call": 0.1
        },
        "flop": {
            "br": 0.1,
            "vbr": 0.85,
            "cr": 0.3,
            "mbr": 0.25,
            "strong_raise": 0.58,
            "strong_call": 0.35,
            "strong_fold": 0.07,
            "med_raise": 0.12,
            "weak_call": 0.08
        },
        "turn": {
            "br": 0.08,
            "vbr": 0.85,
            "cr": 0.28,
            "mbr": 0.2,
            "strong_raise": 0.53,
            "strong_call": 0.37,
            "strong_fold": 0.1,
            "med_raise": 0.1,
            "weak_call": 0.06
        },
        "river": {
            "br": 0.05,
            "vbr": 0.8,
            "cr": 0.25,
            "mbr": 0.15,
            "strong_raise": 0.48,
            "strong_call": 0.4,
            "strong_fold": 0.12,
            "med_raise": 0.08,
            "weak_call": 0.05
        }
    },
    "judge_cooperative": {
        "preflop": {
            "br": 0.02,
            "vbr": 0.85,
            "cr": 0.12,
            "mbr": 0.08,
            "strong_raise": 0.75,
            "strong_call": 0.2,
            "strong_fold": 0.05,
            "med_raise": 0.15,
            "weak_call": 0.03
        },
        "flop": {
            "br": 0.05,
            "vbr": 0.8,
            "cr": 0.18,
            "mbr": 0.12,
            "strong_raise": 0.7,
            "strong_call": 0.25,
            "strong_fold": 0.05,
            "med_raise": 0.2,
            "weak_call": 0.08
        },
        "turn": {
            "br": 0.03,
            "vbr": 0.82,
            "cr": 0.15,
            "mbr": 0.1,
            "strong_raise": 0.72,
            "strong_call": 0.23,
            "strong_fold": 0.05,
            "med_raise": 0.18,
            "weak_call": 0.06
        },
        "river": {
            "br": 0.02,
            "vbr": 0.85,
            "cr": 0.12,
            "mbr": 0.08,
            "strong_raise": 0.75,
            "strong_call": 0.2,
            "strong_fold": 0.05,
            "med_raise": 0.15,
            "weak_call": 0.04
        }
    },
    "judge_retaliatory": {
        "preflop": {
            "br": 0.35,
            "vbr": 0.9,
            "cr": 0.08,
            "mbr": 0.45,
            "strong_raise": 0.85,
            "strong_call": 0.12,
            "strong_fold": 0.03,
            "med_raise": 0.55,
            "weak_call": 0.02
        },
        "flop": {
            "br": 0.4,
            "vbr": 0.88,
            "cr": 0.1,
            "mbr": 0.5,
            "strong_raise": 0.8,
            "strong_call": 0.15,
            "strong_fold": 0.05,
            "med_raise": 0.6,
            "weak_call": 0.03
        },
        "turn": {
            "br": 0.32,
            "vbr": 0.85,
            "cr": 0.08,
            "mbr": 0.42,
            "strong_raise": 0.78,
            "strong_call": 0.17,
            "strong_fold": 0.05,
            "med_raise": 0.52,
            "weak_call": 0.02
        },
        "river": {
            "br": 0.28,
            "vbr": 0.88,
            "cr": 0.06,
            "mbr": 0.38,
            "strong_raise": 0.82,
            "strong_call": 0.15,
            "strong_fold": 0.03,
            "med_raise": 0.48,
            "weak_call": 0.01
        }
    }
}
