"""
Phase 3 LLM-Generated Parameters: firestorm
Generated by: claude-sonnet-4-20250514
"""

FIRESTORM_PARAMS = {
    "preflop": {
        "br": 0.7,
        "vbr": 0.98,
        "cr": 0.35,
        "mbr": 0.8,
        "strong_raise": 0.75,
        "strong_call": 0.2,
        "strong_fold": 0.05,
        "med_raise": 0.15,
        "weak_call": 0.4
    },
    "flop": {
        "br": 0.65,
        "vbr": 0.95,
        "cr": 0.3,
        "mbr": 0.75,
        "strong_raise": 0.7,
        "strong_call": 0.25,
        "strong_fold": 0.05,
        "med_raise": 0.2,
        "weak_call": 0.35
    },
    "turn": {
        "br": 0.6,
        "vbr": 0.92,
        "cr": 0.25,
        "mbr": 0.7,
        "strong_raise": 0.65,
        "strong_call": 0.3,
        "strong_fold": 0.05,
        "med_raise": 0.15,
        "weak_call": 0.3
    },
    "river": {
        "br": 0.55,
        "vbr": 0.9,
        "cr": 0.2,
        "mbr": 0.65,
        "strong_raise": 0.6,
        "strong_call": 0.35,
        "strong_fold": 0.05,
        "med_raise": 0.1,
        "weak_call": 0.25
    }
}
