# LLM-generated parameters for The Firestorm (Loose-Aggressive / LAG / Maniac)
# Generated by Claude Sonnet via phase3/generate_params.py

FIRESTORM_PARAMS = {
    "preflop": {
        "br": 0.68, "vbr": 0.97, "cr": 0.68, "mbr": 0.78,
        "strong_raise": 0.73, "strong_call": 0.24, "strong_fold": 0.03,
        "med_raise": 0.23, "weak_call": 0.38,
    },
    "flop": {
        "br": 0.63, "vbr": 0.94, "cr": 0.63, "mbr": 0.73,
        "strong_raise": 0.68, "strong_call": 0.28, "strong_fold": 0.04,
        "med_raise": 0.19, "weak_call": 0.33,
    },
    "turn": {
        "br": 0.58, "vbr": 0.91, "cr": 0.58, "mbr": 0.68,
        "strong_raise": 0.63, "strong_call": 0.31, "strong_fold": 0.06,
        "med_raise": 0.17, "weak_call": 0.28,
    },
    "river": {
        "br": 0.53, "vbr": 0.88, "cr": 0.53, "mbr": 0.63,
        "strong_raise": 0.58, "strong_call": 0.34, "strong_fold": 0.08,
        "med_raise": 0.14, "weak_call": 0.23,
    },
}
