"""
Phase 3 LLM-Generated Parameters: judge
Generated by: claude-sonnet-4-20250514
"""

JUDGE_PRE_TRIGGER = {
    "preflop": {
        "br": 0.02,
        "vbr": 0.85,
        "cr": 0.12,
        "mbr": 0.08,
        "strong_raise": 0.75,
        "strong_call": 0.2,
        "strong_fold": 0.05,
        "med_raise": 0.15,
        "weak_call": 0.03
    },
    "flop": {
        "br": 0.05,
        "vbr": 0.8,
        "cr": 0.18,
        "mbr": 0.12,
        "strong_raise": 0.7,
        "strong_call": 0.25,
        "strong_fold": 0.05,
        "med_raise": 0.2,
        "weak_call": 0.08
    },
    "turn": {
        "br": 0.03,
        "vbr": 0.82,
        "cr": 0.15,
        "mbr": 0.1,
        "strong_raise": 0.72,
        "strong_call": 0.23,
        "strong_fold": 0.05,
        "med_raise": 0.18,
        "weak_call": 0.06
    },
    "river": {
        "br": 0.02,
        "vbr": 0.85,
        "cr": 0.12,
        "mbr": 0.08,
        "strong_raise": 0.75,
        "strong_call": 0.2,
        "strong_fold": 0.05,
        "med_raise": 0.15,
        "weak_call": 0.04
    }
}

JUDGE_POST_TRIGGER = {
    "preflop": {
        "br": 0.35,
        "vbr": 0.9,
        "cr": 0.08,
        "mbr": 0.45,
        "strong_raise": 0.85,
        "strong_call": 0.12,
        "strong_fold": 0.03,
        "med_raise": 0.55,
        "weak_call": 0.02
    },
    "flop": {
        "br": 0.4,
        "vbr": 0.88,
        "cr": 0.1,
        "mbr": 0.5,
        "strong_raise": 0.8,
        "strong_call": 0.15,
        "strong_fold": 0.05,
        "med_raise": 0.6,
        "weak_call": 0.03
    },
    "turn": {
        "br": 0.32,
        "vbr": 0.85,
        "cr": 0.08,
        "mbr": 0.42,
        "strong_raise": 0.78,
        "strong_call": 0.17,
        "strong_fold": 0.05,
        "med_raise": 0.52,
        "weak_call": 0.02
    },
    "river": {
        "br": 0.28,
        "vbr": 0.88,
        "cr": 0.06,
        "mbr": 0.38,
        "strong_raise": 0.82,
        "strong_call": 0.15,
        "strong_fold": 0.03,
        "med_raise": 0.48,
        "weak_call": 0.01
    }
}
