# LLM-generated parameters for The Mirror (Tit-for-Tat / Mimicry)
# Generated by Claude Sonnet via phase3/generate_params.py
#
# MIRROR_DEFAULT_PARAMS: default parameters before mirroring kicks in

MIRROR_DEFAULT_PARAMS = {
    "preflop": {
        "br": 0.13, "vbr": 0.88, "cr": 0.36, "mbr": 0.28,
        "strong_raise": 0.60, "strong_call": 0.35, "strong_fold": 0.05,
        "med_raise": 0.06, "weak_call": 0.11,
    },
    "flop": {
        "br": 0.11, "vbr": 0.83, "cr": 0.33, "mbr": 0.23,
        "strong_raise": 0.56, "strong_call": 0.37, "strong_fold": 0.07,
        "med_raise": 0.05, "weak_call": 0.09,
    },
    "turn": {
        "br": 0.09, "vbr": 0.83, "cr": 0.28, "mbr": 0.18,
        "strong_raise": 0.51, "strong_call": 0.40, "strong_fold": 0.09,
        "med_raise": 0.04, "weak_call": 0.07,
    },
    "river": {
        "br": 0.06, "vbr": 0.78, "cr": 0.23, "mbr": 0.14,
        "strong_raise": 0.46, "strong_call": 0.43, "strong_fold": 0.11,
        "med_raise": 0.03, "weak_call": 0.06,
    },
}
