"""
Phase 3 LLM-Generated Parameters: mirror
Generated by: claude-sonnet-4-20250514
"""

MIRROR_PARAMS = {
    "preflop": {
        "br": 0.12,
        "vbr": 0.9,
        "cr": 0.33,
        "mbr": 0.3,
        "strong_raise": 0.62,
        "strong_call": 0.33,
        "strong_fold": 0.05,
        "med_raise": 0.15,
        "weak_call": 0.1
    },
    "flop": {
        "br": 0.1,
        "vbr": 0.85,
        "cr": 0.3,
        "mbr": 0.25,
        "strong_raise": 0.58,
        "strong_call": 0.35,
        "strong_fold": 0.07,
        "med_raise": 0.12,
        "weak_call": 0.08
    },
    "turn": {
        "br": 0.08,
        "vbr": 0.85,
        "cr": 0.28,
        "mbr": 0.2,
        "strong_raise": 0.53,
        "strong_call": 0.37,
        "strong_fold": 0.1,
        "med_raise": 0.1,
        "weak_call": 0.06
    },
    "river": {
        "br": 0.05,
        "vbr": 0.8,
        "cr": 0.25,
        "mbr": 0.15,
        "strong_raise": 0.48,
        "strong_call": 0.4,
        "strong_fold": 0.12,
        "med_raise": 0.08,
        "weak_call": 0.05
    }
}
