# LLM-generated parameters for The Oracle (Nash Equilibrium)
# Generated by Claude Sonnet via phase3/generate_params.py

ORACLE_PARAMS = {
    "preflop": {
        "br": 0.31, "vbr": 0.93, "cr": 0.35, "mbr": 0.48,
        "strong_raise": 0.58, "strong_call": 0.37, "strong_fold": 0.05,
        "med_raise": 0.06, "weak_call": 0.16,
    },
    "flop": {
        "br": 0.32, "vbr": 0.88, "cr": 0.34, "mbr": 0.43,
        "strong_raise": 0.57, "strong_call": 0.37, "strong_fold": 0.06,
        "med_raise": 0.06, "weak_call": 0.14,
    },
    "turn": {
        "br": 0.30, "vbr": 0.84, "cr": 0.32, "mbr": 0.38,
        "strong_raise": 0.53, "strong_call": 0.39, "strong_fold": 0.08,
        "med_raise": 0.05, "weak_call": 0.11,
    },
    "river": {
        "br": 0.29, "vbr": 0.78, "cr": 0.31, "mbr": 0.34,
        "strong_raise": 0.48, "strong_call": 0.42, "strong_fold": 0.10,
        "med_raise": 0.04, "weak_call": 0.09,
    },
}
