"""
Phase 3 LLM-Generated Parameters: oracle
Generated by: claude-sonnet-4-20250514
"""

ORACLE_PARAMS = {
    "preflop": {
        "br": 0.33,
        "vbr": 0.9,
        "cr": 0.33,
        "mbr": 0.45,
        "strong_raise": 0.5,
        "strong_call": 0.4,
        "strong_fold": 0.1,
        "med_raise": 0.15,
        "weak_call": 0.12
    },
    "flop": {
        "br": 0.33,
        "vbr": 0.9,
        "cr": 0.33,
        "mbr": 0.45,
        "strong_raise": 0.5,
        "strong_call": 0.4,
        "strong_fold": 0.1,
        "med_raise": 0.15,
        "weak_call": 0.1
    },
    "turn": {
        "br": 0.3,
        "vbr": 0.85,
        "cr": 0.33,
        "mbr": 0.4,
        "strong_raise": 0.5,
        "strong_call": 0.4,
        "strong_fold": 0.1,
        "med_raise": 0.12,
        "weak_call": 0.08
    },
    "river": {
        "br": 0.28,
        "vbr": 0.8,
        "cr": 0.33,
        "mbr": 0.35,
        "strong_raise": 0.5,
        "strong_call": 0.4,
        "strong_fold": 0.1,
        "med_raise": 0.1,
        "weak_call": 0.06
    }
}
