"""
Phase 3 LLM-Generated Parameters: phantom
Generated by: claude-sonnet-4-20250514
"""

PHANTOM_PARAMS = {
    "preflop": {
        "br": 0.65,
        "vbr": 0.7,
        "cr": 0.55,
        "mbr": 0.6,
        "strong_raise": 0.45,
        "strong_call": 0.4,
        "strong_fold": 0.15,
        "med_raise": 0.25,
        "weak_call": 0.35
    },
    "flop": {
        "br": 0.55,
        "vbr": 0.6,
        "cr": 0.45,
        "mbr": 0.5,
        "strong_raise": 0.35,
        "strong_call": 0.45,
        "strong_fold": 0.2,
        "med_raise": 0.2,
        "weak_call": 0.3
    },
    "turn": {
        "br": 0.5,
        "vbr": 0.55,
        "cr": 0.4,
        "mbr": 0.45,
        "strong_raise": 0.3,
        "strong_call": 0.45,
        "strong_fold": 0.25,
        "med_raise": 0.15,
        "weak_call": 0.22
    },
    "river": {
        "br": 0.45,
        "vbr": 0.5,
        "cr": 0.35,
        "mbr": 0.4,
        "strong_raise": 0.25,
        "strong_call": 0.45,
        "strong_fold": 0.3,
        "med_raise": 0.1,
        "weak_call": 0.15
    }
}
