# LLM-generated parameters for The Phantom (Deceiver / False Signal Generator)
# Generated by Claude Sonnet via phase3/generate_params.py

PHANTOM_PARAMS = {
    "preflop": {
        "br": 0.58, "vbr": 0.63, "cr": 0.28, "mbr": 0.53,
        "strong_raise": 0.38, "strong_call": 0.46, "strong_fold": 0.16,
        "med_raise": 0.07, "weak_call": 0.33,
    },
    "flop": {
        "br": 0.53, "vbr": 0.58, "cr": 0.23, "mbr": 0.48,
        "strong_raise": 0.33, "strong_call": 0.46, "strong_fold": 0.21,
        "med_raise": 0.05, "weak_call": 0.28,
    },
    "turn": {
        "br": 0.48, "vbr": 0.53, "cr": 0.18, "mbr": 0.43,
        "strong_raise": 0.28, "strong_call": 0.46, "strong_fold": 0.26,
        "med_raise": 0.04, "weak_call": 0.20,
    },
    "river": {
        "br": 0.43, "vbr": 0.48, "cr": 0.14, "mbr": 0.38,
        "strong_raise": 0.24, "strong_call": 0.46, "strong_fold": 0.30,
        "med_raise": 0.03, "weak_call": 0.14,
    },
}
