"""
Phase 3 LLM-Generated Parameters: predator
Generated by: claude-sonnet-4-20250514
"""

PREDATOR_PARAMS = {
    "preflop": {
        "br": 0.25,
        "vbr": 0.9,
        "cr": 0.35,
        "mbr": 0.4,
        "strong_raise": 0.6,
        "strong_call": 0.35,
        "strong_fold": 0.05,
        "med_raise": 0.15,
        "weak_call": 0.12
    },
    "flop": {
        "br": 0.25,
        "vbr": 0.85,
        "cr": 0.32,
        "mbr": 0.35,
        "strong_raise": 0.55,
        "strong_call": 0.38,
        "strong_fold": 0.07,
        "med_raise": 0.12,
        "weak_call": 0.1
    },
    "turn": {
        "br": 0.2,
        "vbr": 0.8,
        "cr": 0.3,
        "mbr": 0.3,
        "strong_raise": 0.5,
        "strong_call": 0.42,
        "strong_fold": 0.08,
        "med_raise": 0.1,
        "weak_call": 0.08
    },
    "river": {
        "br": 0.15,
        "vbr": 0.8,
        "cr": 0.28,
        "mbr": 0.25,
        "strong_raise": 0.45,
        "strong_call": 0.45,
        "strong_fold": 0.1,
        "med_raise": 0.08,
        "weak_call": 0.06
    }
}
