# LLM-generated parameters for The Predator (Exploiter / Shark)
# Generated by Claude Sonnet via phase3/generate_params.py
#
# PREDATOR_BASELINE_PARAMS: default when no opponent classified >60%
# PREDATOR_EXPLOIT: per-opponent-type exploit adjustments

PREDATOR_BASELINE_PARAMS = {
    "preflop": {
        "br": 0.23, "vbr": 0.88, "cr": 0.33, "mbr": 0.38,
        "strong_raise": 0.58, "strong_call": 0.37, "strong_fold": 0.05,
        "med_raise": 0.06, "weak_call": 0.13,
    },
    "flop": {
        "br": 0.23, "vbr": 0.83, "cr": 0.33, "mbr": 0.33,
        "strong_raise": 0.53, "strong_call": 0.39, "strong_fold": 0.08,
        "med_raise": 0.05, "weak_call": 0.11,
    },
    "turn": {
        "br": 0.18, "vbr": 0.78, "cr": 0.28, "mbr": 0.28,
        "strong_raise": 0.48, "strong_call": 0.42, "strong_fold": 0.10,
        "med_raise": 0.04, "weak_call": 0.09,
    },
    "river": {
        "br": 0.14, "vbr": 0.78, "cr": 0.28, "mbr": 0.23,
        "strong_raise": 0.43, "strong_call": 0.44, "strong_fold": 0.13,
        "med_raise": 0.03, "weak_call": 0.07,
    },
}

PREDATOR_EXPLOIT = {
    "oracle": {
        "preflop": {"br": 0.31, "vbr": 0.88, "cr": 0.31, "mbr": 0.38},
        "flop":    {"br": 0.31, "vbr": 0.83, "cr": 0.31, "mbr": 0.33},
        "turn":    {"br": 0.31, "vbr": 0.78, "cr": 0.31, "mbr": 0.28},
        "river":   {"br": 0.31, "vbr": 0.78, "cr": 0.31, "mbr": 0.23},
    },
    "sentinel": {
        "preflop": {"br": 0.43, "vbr": 0.83, "cr": 0.23, "mbr": 0.43},
        "flop":    {"br": 0.43, "vbr": 0.83, "cr": 0.23, "mbr": 0.38},
        "turn":    {"br": 0.38, "vbr": 0.80, "cr": 0.20, "mbr": 0.33},
        "river":   {"br": 0.36, "vbr": 0.78, "cr": 0.18, "mbr": 0.28},
    },
    "firestorm": {
        "preflop": {"br": 0.09, "vbr": 0.93, "cr": 0.58, "mbr": 0.28},
        "flop":    {"br": 0.09, "vbr": 0.93, "cr": 0.58, "mbr": 0.23},
        "turn":    {"br": 0.07, "vbr": 0.90, "cr": 0.53, "mbr": 0.20},
        "river":   {"br": 0.04, "vbr": 0.88, "cr": 0.53, "mbr": 0.16},
    },
    "wall": {
        "preflop": {"br": 0.04, "vbr": 0.97, "cr": 0.33, "mbr": 0.23},
        "flop":    {"br": 0.03, "vbr": 0.97, "cr": 0.33, "mbr": 0.18},
        "turn":    {"br": 0.02, "vbr": 0.95, "cr": 0.28, "mbr": 0.16},
        "river":   {"br": 0.01, "vbr": 0.93, "cr": 0.28, "mbr": 0.13},
    },
    "phantom": {
        "preflop": {"br": 0.14, "vbr": 0.88, "cr": 0.53, "mbr": 0.33},
        "flop":    {"br": 0.11, "vbr": 0.86, "cr": 0.53, "mbr": 0.28},
        "turn":    {"br": 0.09, "vbr": 0.83, "cr": 0.48, "mbr": 0.23},
        "river":   {"br": 0.07, "vbr": 0.80, "cr": 0.48, "mbr": 0.20},
    },
    "predator_baseline": {
        "preflop": {"br": 0.31, "vbr": 0.88, "cr": 0.31, "mbr": 0.38},
        "flop":    {"br": 0.31, "vbr": 0.83, "cr": 0.31, "mbr": 0.33},
        "turn":    {"br": 0.31, "vbr": 0.78, "cr": 0.31, "mbr": 0.28},
        "river":   {"br": 0.31, "vbr": 0.78, "cr": 0.31, "mbr": 0.23},
    },
    "mirror_default": {
        "preflop": {"br": 0.18, "vbr": 0.88, "cr": 0.33, "mbr": 0.33},
        "flop":    {"br": 0.16, "vbr": 0.86, "cr": 0.33, "mbr": 0.28},
        "turn":    {"br": 0.14, "vbr": 0.83, "cr": 0.30, "mbr": 0.23},
        "river":   {"br": 0.11, "vbr": 0.80, "cr": 0.28, "mbr": 0.20},
    },
    "judge_cooperative": {
        "preflop": {"br": 0.14, "vbr": 0.88, "cr": 0.33, "mbr": 0.33},
        "flop":    {"br": 0.11, "vbr": 0.86, "cr": 0.31, "mbr": 0.28},
        "turn":    {"br": 0.09, "vbr": 0.83, "cr": 0.28, "mbr": 0.23},
        "river":   {"br": 0.07, "vbr": 0.80, "cr": 0.26, "mbr": 0.18},
    },
}
