"""
Phase 3 LLM-Generated Parameters: sentinel
Generated by: claude-sonnet-4-20250514
"""

SENTINEL_PARAMS = {
    "preflop": {
        "br": 0.1,
        "vbr": 0.95,
        "cr": 0.25,
        "mbr": 0.15,
        "strong_raise": 0.65,
        "strong_call": 0.3,
        "strong_fold": 0.05,
        "med_raise": 0.05,
        "weak_call": 0.1
    },
    "flop": {
        "br": 0.08,
        "vbr": 0.9,
        "cr": 0.3,
        "mbr": 0.25,
        "strong_raise": 0.6,
        "strong_call": 0.35,
        "strong_fold": 0.05,
        "med_raise": 0.1,
        "weak_call": 0.08
    },
    "turn": {
        "br": 0.08,
        "vbr": 0.9,
        "cr": 0.32,
        "mbr": 0.2,
        "strong_raise": 0.55,
        "strong_call": 0.4,
        "strong_fold": 0.05,
        "med_raise": 0.08,
        "weak_call": 0.06
    },
    "river": {
        "br": 0.05,
        "vbr": 0.85,
        "cr": 0.35,
        "mbr": 0.15,
        "strong_raise": 0.5,
        "strong_call": 0.4,
        "strong_fold": 0.1,
        "med_raise": 0.05,
        "weak_call": 0.04
    }
}
