# LLM-generated parameters for The Sentinel (Tight-Aggressive / TAG)
# Generated by Claude Sonnet via phase3/generate_params.py

SENTINEL_PARAMS = {
    "preflop": {
        "br": 0.11, "vbr": 0.93, "cr": 0.38, "mbr": 0.28,
        "strong_raise": 0.63, "strong_call": 0.32, "strong_fold": 0.05,
        "med_raise": 0.06, "weak_call": 0.11,
    },
    "flop": {
        "br": 0.09, "vbr": 0.88, "cr": 0.33, "mbr": 0.23,
        "strong_raise": 0.58, "strong_call": 0.36, "strong_fold": 0.06,
        "med_raise": 0.05, "weak_call": 0.09,
    },
    "turn": {
        "br": 0.07, "vbr": 0.88, "cr": 0.28, "mbr": 0.18,
        "strong_raise": 0.54, "strong_call": 0.39, "strong_fold": 0.07,
        "med_raise": 0.04, "weak_call": 0.07,
    },
    "river": {
        "br": 0.04, "vbr": 0.83, "cr": 0.23, "mbr": 0.13,
        "strong_raise": 0.49, "strong_call": 0.41, "strong_fold": 0.10,
        "med_raise": 0.03, "weak_call": 0.05,
    },
}
