"""
Phase 3 LLM-Generated Parameters: wall
Generated by: claude-sonnet-4-20250514
"""

WALL_PARAMS = {
    "preflop": {
        "br": 0.01,
        "vbr": 0.25,
        "cr": 0.85,
        "mbr": 0.08,
        "strong_raise": 0.02,
        "strong_call": 0.96,
        "strong_fold": 0.02,
        "med_raise": 0.01,
        "weak_call": 0.55
    },
    "flop": {
        "br": 0.05,
        "vbr": 0.5,
        "cr": 0.82,
        "mbr": 0.12,
        "strong_raise": 0.12,
        "strong_call": 0.82,
        "strong_fold": 0.06,
        "med_raise": 0.03,
        "weak_call": 0.5
    },
    "turn": {
        "br": 0.03,
        "vbr": 0.45,
        "cr": 0.82,
        "mbr": 0.1,
        "strong_raise": 0.1,
        "strong_call": 0.82,
        "strong_fold": 0.08,
        "med_raise": 0.02,
        "weak_call": 0.42
    },
    "river": {
        "br": 0.02,
        "vbr": 0.4,
        "cr": 0.82,
        "mbr": 0.08,
        "strong_raise": 0.08,
        "strong_call": 0.82,
        "strong_fold": 0.1,
        "med_raise": 0.01,
        "weak_call": 0.35
    }
}
