# LLM-generated parameters for The Wall (Passive / Calling Station)
# Generated by Claude Sonnet via phase3/generate_params.py

WALL_PARAMS = {
    "preflop": {
        "br": 0.04, "vbr": 0.53, "cr": 0.78, "mbr": 0.14,
        "strong_raise": 0.14, "strong_call": 0.81, "strong_fold": 0.05,
        "med_raise": 0.03, "weak_call": 0.53,
    },
    "flop": {
        "br": 0.04, "vbr": 0.48, "cr": 0.73, "mbr": 0.11,
        "strong_raise": 0.11, "strong_call": 0.83, "strong_fold": 0.06,
        "med_raise": 0.02, "weak_call": 0.48,
    },
    "turn": {
        "br": 0.03, "vbr": 0.43, "cr": 0.68, "mbr": 0.09,
        "strong_raise": 0.09, "strong_call": 0.83, "strong_fold": 0.08,
        "med_raise": 0.02, "weak_call": 0.40,
    },
    "river": {
        "br": 0.02, "vbr": 0.38, "cr": 0.63, "mbr": 0.07,
        "strong_raise": 0.07, "strong_call": 0.83, "strong_fold": 0.10,
        "med_raise": 0.01, "weak_call": 0.33,
    },
}
