#!/usr/bin/env python3
"""
Phase 3 — LLM Parameter Generation Script

Reads the personality spec files from phase3/personality_specs/, constructs
structured prompts with the parameter template (keys and types only, no
Phase 1 values), calls the Anthropic API to generate archetype parameters,
validates the output, and saves to phase3/generated_params/.

Usage::

    export ANTHROPIC_API_KEY="sk-ant-..."
    python3 phase3/generate_params.py

Requirements::

    pip install anthropic

The script will ERROR-EXIT if ANTHROPIC_API_KEY is not set. There is no
offline fallback — parameters MUST be generated by the LLM.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Fail fast if no API key
# ---------------------------------------------------------------------------
API_KEY = os.environ.get("ANTHROPIC_API_KEY")
if not API_KEY:
    print(
        "ERROR: ANTHROPIC_API_KEY environment variable is not set.\n"
        "Set it before running this script:\n"
        "  export ANTHROPIC_API_KEY='sk-ant-...'\n",
        file=sys.stderr,
    )
    sys.exit(1)

import anthropic  # noqa: E402 — import after the key check

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PHASE3_DIR = Path(__file__).resolve().parent
SPECS_DIR = PHASE3_DIR / "personality_specs"
OUTPUT_DIR = PHASE3_DIR / "generated_params"

# ---------------------------------------------------------------------------
# The 8 archetypes to generate parameters for
# ---------------------------------------------------------------------------
ARCHETYPES = [
    "oracle",
    "sentinel",
    "firestorm",
    "wall",
    "phantom",
    "predator",
    "mirror",
    "judge",
]

# Judge has two parameter sets: cooperative and retaliatory
JUDGE_STATES = ["judge_cooperative", "judge_retaliatory"]

# ---------------------------------------------------------------------------
# Parameter structure template — keys and types ONLY, no values
# ---------------------------------------------------------------------------
# This is the structure each archetype's per-round params must follow.
# The LLM must fill in float values for each key.
PARAM_TEMPLATE = {
    "rounds": ["preflop", "flop", "turn", "river"],
    "per_round_keys": {
        "br": "float in [0.0, 1.0] — Bluff Rate: P(bet | Weak hand)",
        "vbr": "float in [0.0, 1.0] — Value Bet Rate: P(bet | Strong hand)",
        "cr": "float in [0.0, 1.0] — Call Rate: P(call | facing bet, Medium hand)",
        "mbr": "float in [0.0, 1.0] — Medium Hand Bet Rate: P(bet | Medium hand)",
        "strong_raise": "float in [0.0, 1.0] — P(raise | Strong hand, facing bet)",
        "strong_call": "float in [0.0, 1.0] — P(call | Strong hand, facing bet)",
        "strong_fold": "float in [0.0, 1.0] — P(fold | Strong hand, facing bet)",
        "med_raise": "float in [0.0, 1.0] — P(raise | Medium hand, facing bet)",
        "weak_call": "float in [0.0, 1.0] — P(call | Weak hand, facing bet)",
    },
    "constraints": [
        "All values must be floats in [0.0, 1.0]",
        "For each round: strong_raise + strong_call + strong_fold must sum to ~1.0 (tolerance 0.05)",
        "br should generally decrease from preflop to river (players bluff less on later streets)",
        "vbr should generally decrease from preflop to river (value betting becomes more selective)",
        "weak_call should generally decrease from preflop to river (folding increases with bet size)",
        "med_raise should be small (0.01-0.25) — medium hands rarely raise",
    ],
}

# For Predator, we also need an exploit table
EXPLOIT_TEMPLATE = {
    "description": (
        "Per-opponent-type exploit parameters. When the Predator classifies "
        "an opponent with >60% posterior confidence, it blends toward these "
        "parameters. Only the 4 core metrics that CHANGE from baseline are "
        "listed: br, vbr, cr, mbr."
    ),
    "target_types": [
        "oracle",
        "sentinel",
        "firestorm",
        "wall",
        "phantom",
        "predator_baseline",
        "mirror_default",
        "judge_cooperative",
    ],
    "per_round_keys": {
        "br": "float in [0.0, 1.0] — adjusted bluff rate vs this target",
        "vbr": "float in [0.0, 1.0] — adjusted value bet rate vs this target",
        "cr": "float in [0.0, 1.0] — adjusted call rate vs this target",
        "mbr": "float in [0.0, 1.0] — adjusted medium bet rate vs this target",
    },
}


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def _read_spec(archetype: str) -> str:
    """Read the personality spec markdown for a given archetype."""
    spec_path = SPECS_DIR / f"{archetype}.md"
    if not spec_path.exists():
        raise FileNotFoundError(
            f"Personality spec not found: {spec_path}\n"
            f"Run Stage 1 first to create the spec files."
        )
    return spec_path.read_text(encoding="utf-8")


def _build_system_prompt() -> str:
    """System prompt establishing the role and rules."""
    return """\
You are an expert poker strategist and game theorist. Your task is to generate
numerical parameter tables for AI poker agents in a Limit Texas Hold'em
simulation.

CRITICAL RULES:
1. Output ONLY valid JSON — no markdown, no commentary, no explanation.
2. Every value must be a float between 0.0 and 1.0.
3. For each round, strong_raise + strong_call + strong_fold must sum to
   approximately 1.0 (within 0.05 tolerance).
4. Parameters must be INTERNALLY CONSISTENT with the personality description
   and quantitative targets provided.
5. Do NOT copy Phase 1 values — generate fresh parameters that match the
   described personality and behavioral targets.
6. Think about what each parameter means in terms of poker strategy before
   choosing values.

GAME CONTEXT:
- Limit Texas Hold'em, 8 players, 200-chip starting stacks
- Small blind = 1, Big blind = 2
- Small bet = 2 (preflop/flop), Big bet = 4 (turn/river)
- Bet cap = 4 per round (1 bet + 3 raises)
- Hand strength buckets: Strong (>66% equity), Medium (33-66%), Weak (<33%)
"""


def _build_archetype_prompt(archetype: str, spec_text: str) -> str:
    """Build the user prompt for generating one archetype's parameters."""
    template_json = json.dumps(PARAM_TEMPLATE, indent=2)

    if archetype == "judge":
        return f"""\
Generate parameters for THE JUDGE archetype. The Judge has TWO parameter sets:
1. "judge_cooperative" — used when cooperating (default state)
2. "judge_retaliatory" — used when retaliating against a bluffer (triggered
   after tau=5 confirmed bluffs from a specific opponent)

PERSONALITY SPEC:
{spec_text}

PARAMETER STRUCTURE (generate this for BOTH states):
{template_json}

Return a JSON object with this exact structure:
{{
  "judge_cooperative": {{
    "preflop": {{"br": ..., "vbr": ..., "cr": ..., "mbr": ..., "strong_raise": ..., "strong_call": ..., "strong_fold": ..., "med_raise": ..., "weak_call": ...}},
    "flop": {{...}},
    "turn": {{...}},
    "river": {{...}}
  }},
  "judge_retaliatory": {{
    "preflop": {{...}},
    "flop": {{...}},
    "turn": {{...}},
    "river": {{...}}
  }}
}}

The cooperative state should be tight and honest (low br, high vbr).
The retaliatory state should be aggressive (high br, low cr, high mbr).
"""

    if archetype == "predator":
        exploit_json = json.dumps(EXPLOIT_TEMPLATE, indent=2)
        return f"""\
Generate parameters for THE PREDATOR archetype. The Predator has:
1. "predator_baseline" — default parameters when no opponent is classified
2. "predator_exploit" — per-opponent-type exploit adjustments

PERSONALITY SPEC:
{spec_text}

BASELINE PARAMETER STRUCTURE:
{template_json}

EXPLOIT TABLE STRUCTURE:
{exploit_json}

Return a JSON object with this exact structure:
{{
  "predator_baseline": {{
    "preflop": {{"br": ..., "vbr": ..., "cr": ..., "mbr": ..., "strong_raise": ..., "strong_call": ..., "strong_fold": ..., "med_raise": ..., "weak_call": ...}},
    "flop": {{...}},
    "turn": {{...}},
    "river": {{...}}
  }},
  "predator_exploit": {{
    "oracle": {{
      "preflop": {{"br": ..., "vbr": ..., "cr": ..., "mbr": ...}},
      "flop": {{...}}, "turn": {{...}}, "river": {{...}}
    }},
    "sentinel": {{...}},
    "firestorm": {{...}},
    "wall": {{...}},
    "phantom": {{...}},
    "predator_baseline": {{...}},
    "mirror_default": {{...}},
    "judge_cooperative": {{...}}
  }}
}}

Key exploit strategies:
- vs Wall: never bluff, max value bet (Wall never folds)
- vs Firestorm: stop bluffing, call down bluffs, max value bet
- vs Sentinel: bluff more (TAG folds too much), call less
- vs Phantom: raise more, call down bluffs
- vs Oracle/Predator: play near-equilibrium (nothing to exploit)
- vs Mirror/Judge: cautious play, avoid triggering retaliation
"""

    # Map archetype names to the param key names used in the system
    param_key = archetype
    if archetype == "mirror":
        param_key = "mirror_default"

    return f"""\
Generate parameters for THE {archetype.upper()} archetype.

PERSONALITY SPEC:
{spec_text}

PARAMETER STRUCTURE:
{template_json}

Return a JSON object with this exact structure:
{{
  "{param_key}": {{
    "preflop": {{"br": ..., "vbr": ..., "cr": ..., "mbr": ..., "strong_raise": ..., "strong_call": ..., "strong_fold": ..., "med_raise": ..., "weak_call": ...}},
    "flop": {{...}},
    "turn": {{...}},
    "river": {{...}}
  }}
}}
"""


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

REQUIRED_KEYS = [
    "br", "vbr", "cr", "mbr",
    "strong_raise", "strong_call", "strong_fold",
    "med_raise", "weak_call",
]
ROUNDS = ["preflop", "flop", "turn", "river"]


def _validate_round_params(params: dict, label: str) -> List[str]:
    """Validate a single round's parameter dict. Returns list of errors."""
    errors: List[str] = []
    for key in REQUIRED_KEYS:
        if key not in params:
            errors.append(f"{label}: missing key '{key}'")
            continue
        val = params[key]
        if not isinstance(val, (int, float)):
            errors.append(f"{label}: '{key}' is not a number (got {type(val).__name__})")
            continue
        if val < 0.0 or val > 1.0:
            errors.append(f"{label}: '{key}' = {val} is outside [0.0, 1.0]")

    # Check strong_raise + strong_call + strong_fold ≈ 1.0
    sr = params.get("strong_raise", 0)
    sc = params.get("strong_call", 0)
    sf = params.get("strong_fold", 0)
    if isinstance(sr, (int, float)) and isinstance(sc, (int, float)) and isinstance(sf, (int, float)):
        total = sr + sc + sf
        if abs(total - 1.0) > 0.05:
            errors.append(
                f"{label}: strong_raise + strong_call + strong_fold = {total:.3f} "
                f"(should be ~1.0)"
            )
    return errors


def _validate_archetype_params(data: dict, archetype_key: str) -> List[str]:
    """Validate a full archetype parameter set (4 rounds)."""
    errors: List[str] = []
    if archetype_key not in data:
        errors.append(f"Missing top-level key '{archetype_key}'")
        return errors
    archetype_data = data[archetype_key]
    for round_name in ROUNDS:
        if round_name not in archetype_data:
            errors.append(f"{archetype_key}: missing round '{round_name}'")
            continue
        label = f"{archetype_key}.{round_name}"
        errors.extend(_validate_round_params(archetype_data[round_name], label))
    return errors


def _validate_exploit_table(data: dict) -> List[str]:
    """Validate the Predator exploit table."""
    errors: List[str] = []
    if "predator_exploit" not in data:
        errors.append("Missing 'predator_exploit' key")
        return errors
    exploit = data["predator_exploit"]
    exploit_keys = ["br", "vbr", "cr", "mbr"]
    for target in EXPLOIT_TEMPLATE["target_types"]:
        if target not in exploit:
            errors.append(f"predator_exploit: missing target '{target}'")
            continue
        for round_name in ROUNDS:
            if round_name not in exploit[target]:
                errors.append(f"predator_exploit.{target}: missing round '{round_name}'")
                continue
            for key in exploit_keys:
                label = f"predator_exploit.{target}.{round_name}"
                if key not in exploit[target][round_name]:
                    errors.append(f"{label}: missing key '{key}'")
                    continue
                val = exploit[target][round_name][key]
                if not isinstance(val, (int, float)):
                    errors.append(f"{label}: '{key}' is not a number")
                elif val < 0.0 or val > 1.0:
                    errors.append(f"{label}: '{key}' = {val} outside [0.0, 1.0]")
    return errors


# ---------------------------------------------------------------------------
# API call with retry
# ---------------------------------------------------------------------------

MAX_RETRIES = 3


def _call_api(
    client: anthropic.Anthropic,
    system_prompt: str,
    user_prompt: str,
) -> str:
    """Call the Anthropic API and return the text response."""
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )
    return message.content[0].text


def _parse_json_response(text: str) -> dict:
    """Parse JSON from API response, stripping any markdown fences."""
    cleaned = text.strip()
    # Strip markdown code fences if present
    if cleaned.startswith("```"):
        # Remove opening fence (```json or ```)
        first_newline = cleaned.index("\n")
        cleaned = cleaned[first_newline + 1:]
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].rstrip()
    return json.loads(cleaned)


def _generate_archetype(
    client: anthropic.Anthropic,
    archetype: str,
    system_prompt: str,
) -> Dict[str, Any]:
    """Generate and validate parameters for one archetype. Retries on failure."""
    spec_text = _read_spec(archetype)
    user_prompt = _build_archetype_prompt(archetype, spec_text)

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"  Generating {archetype} (attempt {attempt}/{MAX_RETRIES})...")
        try:
            response_text = _call_api(client, system_prompt, user_prompt)
            data = _parse_json_response(response_text)
        except (json.JSONDecodeError, ValueError, IndexError) as e:
            print(f"    JSON parse error: {e}")
            if attempt == MAX_RETRIES:
                raise RuntimeError(
                    f"Failed to generate valid JSON for {archetype} "
                    f"after {MAX_RETRIES} attempts"
                ) from e
            continue

        # Validate
        errors: List[str] = []
        if archetype == "judge":
            errors.extend(_validate_archetype_params(data, "judge_cooperative"))
            errors.extend(_validate_archetype_params(data, "judge_retaliatory"))
        elif archetype == "predator":
            errors.extend(_validate_archetype_params(data, "predator_baseline"))
            errors.extend(_validate_exploit_table(data))
        elif archetype == "mirror":
            errors.extend(_validate_archetype_params(data, "mirror_default"))
        else:
            errors.extend(_validate_archetype_params(data, archetype))

        if errors:
            print(f"    Validation errors ({len(errors)}):")
            for err in errors[:5]:
                print(f"      - {err}")
            if len(errors) > 5:
                print(f"      ... and {len(errors) - 5} more")
            if attempt == MAX_RETRIES:
                raise RuntimeError(
                    f"Failed to generate valid params for {archetype} "
                    f"after {MAX_RETRIES} attempts. Errors:\n"
                    + "\n".join(errors)
                )
            continue

        print(f"    OK — {archetype} validated successfully")
        return data

    # Should not reach here, but satisfy type checker
    raise RuntimeError(f"Unreachable: failed to generate {archetype}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    client = anthropic.Anthropic(api_key=API_KEY)
    system_prompt = _build_system_prompt()

    # Collect all generated params into a single combined file
    all_params: Dict[str, Any] = {}
    exploit_table: Optional[Dict[str, Any]] = None

    print(f"Generating parameters for {len(ARCHETYPES)} archetypes...")
    print(f"Model: claude-sonnet-4-20250514")
    print(f"Output: {OUTPUT_DIR}/")
    print()

    for archetype in ARCHETYPES:
        data = _generate_archetype(client, archetype, system_prompt)

        # Save individual archetype file
        out_path = OUTPUT_DIR / f"{archetype}.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        print(f"    Saved: {out_path}")

        # Merge into combined params
        if archetype == "judge":
            all_params["judge_cooperative"] = data["judge_cooperative"]
            all_params["judge_retaliatory"] = data["judge_retaliatory"]
        elif archetype == "predator":
            all_params["predator_baseline"] = data["predator_baseline"]
            exploit_table = data["predator_exploit"]
        elif archetype == "mirror":
            all_params["mirror_default"] = data["mirror_default"]
        else:
            all_params[archetype] = data[archetype]
        print()

    # Build combined output file
    combined = {
        "archetype_params": all_params,
    }
    if exploit_table is not None:
        combined["predator_exploit"] = exploit_table

    # Compute averages for trust model
    averages: Dict[str, Dict[str, float]] = {}
    for key, rounds_data in all_params.items():
        avg: Dict[str, float] = {}
        for metric in ["br", "vbr", "cr", "mbr"]:
            values = [rounds_data[r][metric] for r in ROUNDS]
            avg[metric] = round(sum(values) / len(values), 3)
        averages[key] = avg
    combined["archetype_averages"] = averages

    # Compute honesty scores: honesty = 1 - avg_br
    honesty: Dict[str, float] = {}
    for key, avg in averages.items():
        honesty[key] = round(1.0 - avg["br"], 3)
    combined["honesty_scores"] = honesty

    combined_path = OUTPUT_DIR / "all_params.json"
    with open(combined_path, "w", encoding="utf-8") as f:
        json.dump(combined, f, indent=2)
    print(f"Combined params saved: {combined_path}")

    # Summary
    print()
    print("=" * 60)
    print("GENERATION COMPLETE")
    print("=" * 60)
    print(f"  Archetypes generated: {len(ARCHETYPES)}")
    print(f"  Parameter sets: {len(all_params)}")
    print(f"  Individual files: {OUTPUT_DIR}/<archetype>.json")
    print(f"  Combined file: {combined_path}")
    print()
    print("Archetype averages (for trust model):")
    for key, avg in averages.items():
        print(f"  {key:20s}: br={avg['br']:.3f}  vbr={avg['vbr']:.3f}  "
              f"cr={avg['cr']:.3f}  mbr={avg['mbr']:.3f}")
    print()
    print("Honesty scores:")
    for key, h in honesty.items():
        print(f"  {key:20s}: {h:.3f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
