#!/usr/bin/env python3
# Mechanical port: arXiv bundle main.tex -> TMLR anonymized submission.
# Every kept preamble block is extracted VERBATIM from the source (asserted
# unique); everything else is template mechanics, anonymization removals, or
# neutral markers. Change log written to port_log.json.
import json, re

SRC='/home/user/Poker_trust/arxiv_build/bundle/main.tex'
OUT='/home/user/Poker_trust/tmlr_build/main.tex'
src=open(SRC,encoding='utf-8').read()
LOG=[]
def log(step, action, detail, before=None, after=None):
    LOG.append({'step':step,'action':action,'detail':detail,'before':before,'after':after})

def extract(name, start, end, include_end=True):
    """Extract verbatim block from src between exact anchors (assert unique)."""
    assert src.count(start)==1, f'{name}: start anchor x{src.count(start)}'
    i=src.index(start)
    j=src.index(end, i)
    assert j>=0, f'{name}: end anchor missing'
    j = j+len(end) if include_end else j
    return src[i:j]

# ---------- verbatim kept blocks ----------
colors   = extract('colors',  '\\usepackage{xcolor}', '\\newcommand{\\arch}[1]{\\textbf{#1}}')
draftW   = extract('draftW',  '\\definecolor{draftnew}', '\\newcommand{\\W}[1]{\\textcolor{draftnew}{#1}}')
captions = extract('caption', '\\usepackage{caption}', 'aboveskip=10pt\n}')
tables   = extract('tables',  '\\usepackage{booktabs}', '\\usepackage{multirow}')
tcb      = extract('tcolorbox','\\usepackage[most]{tcolorbox}', 'boxsep=3pt,\n  }\n}')
links    = extract('links',   '\\usepackage{xurl}', 'urlcolor=scienceRed!80!black]{hyperref}')
macros   = extract('macros',  '\\newcommand{\\rtp}', '\\raggedbottom')

# title text verbatim (3 lines from the old title block, sans styling wrapper)
title = ('Trust Dynamics in Multi-Agent Strategic Interaction:\n'
         '  A Simulation Study of Bayesian Reputation Systems in\n'
         '  8-Player Limit Texas Hold\'em')
assert 'Trust Dynamics in Multi-Agent Strategic Interaction:' in src

# abstract text verbatim: from "What if being trustworthy" to "become a bad thing?"
abs_start='      What if being trustworthy cost you something?'
abs_end='does a good reputation become a bad thing?'
abstract = extract('abstract', abs_start, abs_end)

# ---------- new preamble ----------
preamble = f"""% TMLR anonymized submission --- mechanically ported from the verified
% arXiv source bundle. Preamble follows the official TMLR template
% (tmlr.sty from github.com/JmlrOrg/tmlr-style-file); every retained block
% below is copied verbatim from the source. See PORT_REPORT.md.

\\documentclass[10pt]{{article}} % For LaTeX2e
\\usepackage{{tmlr}}
% If accepted, instead use the following line for the camera-ready submission:
%\\usepackage[accepted]{{tmlr}}
% To de-anonymize for preprint servers:
%\\usepackage[preprint]{{tmlr}}

% --- ENCODING ----------------------------------------------------------------
\\usepackage[utf8]{{inputenc}}
\\usepackage{{microtype}}

% --- MATH --------------------------------------------------------------------
\\usepackage{{amsmath}}
\\usepackage{{amssymb}}

% --- COLORS (verbatim from source) --------------------------------------------
{colors}

% --- GRAPHICS & FLOATS ---------------------------------------------------------
\\usepackage{{graphicx}}
\\graphicspath{{{{figures/}}{{./}}}}
\\usepackage{{float}}              % enables [H] placement for in-line figures
\\usepackage{{placeins}}           % \\FloatBarrier to pin figures within sections

{draftW}

% --- CAPTIONS (verbatim from source) -------------------------------------------
{captions}

% --- TABLES (verbatim from source) ---------------------------------------------
{tables}

% --- STORY-HAND BOXES (verbatim from source) -------------------------------------
{tcb}

% --- CITATIONS -------------------------------------------------------------------
% natbib is loaded by tmlr.sty (authoryear, round). The frozen main.bbl was
% generated by BibTeX with plainnat, whose \\bibitem entries carry author-year
% labels and are fully compatible with the TMLR citation style.
\\bibliographystyle{{plainnat}}

% --- LINKS (last) ----------------------------------------------------------------
{links}

% --- CUSTOM COMMANDS (verbatim from source) ----------------------------------------
{macros}

\\title{{{title}}}

% Anonymous submission: with the plain tmlr package (no [accepted]/[preprint]),
% the style prints "Anonymous authors --- Paper under double-blind review"
% regardless of this field. No author-identifying text appears in this source.
\\author{{Anonymous authors\\\\Paper under double-blind review}}

\\begin{{document}}

\\maketitle

\\begin{{abstract}}
{abstract}
\\end{{abstract}}
"""

# ---------- body: from \section{Introduction} to \end{document} ----------
bstart=src.index('\\section{Introduction}')
body=src[bstart:]
log('A','preamble replaced',
    'two-column custom preamble (geometry, mathptmx/helvet, titlesec, fancyhdr footer "Agrawal (year) — N of 12", lastpage, natbib[numbers,round]+\\citenumfont/\\bibnumfmt, researchbadge/category macros, tikz [unused]) -> official TMLR template preamble; colors/captions/tables/boxes/links/macros kept verbatim')
log('A','title block replaced',
    'custom \\twocolumn[...] title block (badge, category line, author, correspondence, boxed abstract, rule, \\thispagestyle{firstpage}) -> \\maketitle + standard abstract environment; title text and abstract text copied verbatim')

# ---------- tail surgeries ----------
# 1. Broader Impact marker before \section*{Sources}
anchor='\\section*{Sources}'
assert body.count(anchor)==1
impact=('\\subsubsection*{Broader Impact Statement}\n'
        '[TODO-BROADER-IMPACT: author to write --- see TODO.md]\n\n')
body=body.replace(anchor, impact+anchor)
log('B','Broader Impact Statement marker inserted',
    'empty \\subsubsection* with [TODO-BROADER-IMPACT] placed before the Sources back-matter, per template convention (template places it after main text, before references)')

# 2. Remove Author contributions paragraph (verbatim to checklist)
contrib=('\\paragraph*{Author contributions.} R.A.\\ conceived the study,\n'
         'implemented the simulation, performed the analysis, and wrote the\n'
         'manuscript.\n\n')
assert body.count(contrib)==1, 'contrib paragraph anchor'
body=body.replace(contrib,'')
log('C','Author contributions paragraph removed (anonymization)',
    'restore for camera-ready — verbatim text preserved in DEANONYMIZATION_CHECKLIST.md',
    before=contrib.strip())

# 3. GitHub URL replacement in Data availability
old_avail=('are available at\n\\url{https://github.com/RachitAgrawal146/Poker_trust}.')
new_avail=('are available in an anonymized repository; the link will be\n'
           'restored in the camera-ready version.')
assert body.count(old_avail)==1, 'availability anchor'
body=body.replace(old_avail,new_avail)
log('C','GitHub URL neutralized (anonymization)',
    'Data and materials availability paragraph',
    before='…are available at \\url{https://github.com/RachitAgrawal146/Poker_trust}.',
    after='…'+new_avail.replace('\n',' '))

# 4. References heading: drop manual \subsection*{References}+\footnotesize
old_refs='\\subsection*{References}\n\\footnotesize\n\\bibliography{references}'
assert body.count(old_refs)==1, 'refs anchor'
body=body.replace(old_refs,'\\bibliography{references}')
log('A','manual References heading + \\footnotesize dropped',
    'thebibliography prints its own References heading under the TMLR/article layout; \\footnotesize was a two-column space hack — template-forced, no text change')

out=preamble+'\n'+body
open(OUT,'w',encoding='utf-8').write(out)
json.dump(LOG,open('/home/user/Poker_trust/tmlr_build/port_log.json','w'),indent=1)
print('ported:',len(out.splitlines()),'lines;',len(LOG),'logged steps')
# residual identity check on the produced tex
for s in ['Rachit','Agrawal','agrawal','Sahyadri','RachitAgrawal146','sahyadrischool']:
    n=out.count(s)
    print(f'  {s!r}: {n}')
